# Generated by Django 4.2.7 on 2023-11-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('time', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
