# Generated by Django 4.2.7 on 2023-11-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
